services:
  - type: web
    name: terroir-agent
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn src.main:app --host 0.0.0.0 --port $PORT
    disk:
      name: terroir-cache
      mountPath: /opt/terroir/data
      sizeGB: 1
    envVars:
      - key: USER_AGENT
        value: terroir-agent
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: GITHUB_PERSONAL_ACCESS_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
    cron:
      - schedule: "0 0 * * 0"
        command: python -m src.tasks.update_docs 